words = [
    "apple", "banana", "grape", "orange", "peach", "pear", "cherry", "lemon", "melon", "plum",
    "carrot", "potato", "tomato", "onion", "pepper", "broccoli", "cabbage", "lettuce", "spinach", "radish",
    "dog", "cat", "rabbit", "horse", "sheep", "goat", "cow", "pig", "duck", "chicken",
    "school", "teacher", "student", "pencil", "paper", "notebook", "eraser", "desk", "chalk", "marker",
    "river", "mountain", "forest", "desert", "ocean", "island", "valley", "hill", "beach", "lake",
    "table", "chair", "bed", "lamp", "window", "door", "mirror", "clock", "couch", "shelf",
    "happy", "sad", "angry", "tired", "excited", "bored", "scared", "nervous", "proud", "curious",
    "summer", "winter", "spring", "autumn", "morning", "evening", "night", "noon", "sunset", "sunrise",
    "bird", "fish", "lion", "tiger", "bear", "zebra", "giraffe", "monkey", "elephant", "panda",
    "car", "truck", "bus", "train", "bicycle", "airplane", "boat", "subway", "scooter", "motorcycle",
    "bread", "cheese", "butter", "milk", "water", "juice", "honey", "salt", "sugar", "coffee",
    "hat", "shirt", "pants", "shoes", "socks", "jacket", "scarf", "gloves", "dress", "sweater",
    "house", "garden", "garage", "fence", "roof", "chimney", "porch", "floor", "wall", "ceiling",
    "music", "movie", "game", "book", "story", "poem", "drawing", "painting", "dance", "song",
    "love", "peace", "hope", "dream", "truth", "trust", "laugh", "smile", "gift", "luck"
]
# Generated by ChatGPT